modifies execution scripts to include `bundle exec`. After installing rails for something else I have to install `gem install github-pages`. After this direct `jekyll server` stopped working and started giving error:
```
/bin/bash /Users/aapa/Projects/knoxxs.github.io/deploy-with-drafts.sh
WARN: Unresolved specs during Gem::Specification.reset:
      timers (~> 4.0.0)
      rb-fsevent (>= 0.9.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/aapa/Projects/knoxxs.github.io/_config.yml
            Source: /Users/aapa/Projects/knoxxs.github.io
       Destination: /Users/aapa/Projects/knoxxs.github.io/_site
      Generating...
  Dependency Error:  Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/04/2015-04-19-mongo-internal.markdown/#excerpt':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet

Process finished with exit code 1
```